[project]
name = "fastapi-s"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "web-service",
]

[tool.uv.sources]
web-service = { workspace = true }
duyi-utils = { workspace = true }

[tool.uv.workspace]
members = [
    "packages/*",
    "apps/*",
]

[dependency-groups]
dev = [
    "debugpy>=1.8.21",
    "pylint>=3.3.0",
    "httpx==0.28.1",
    "pytest==9.1.1",
    "pytest-asyncio==1.4.0",
    "pytest-cov==7.0.0",
    "python-dotenv>=1.2.2",
    "duyi-utils",
]

[tool.pytest.ini_options]
asyncio_mode = "auto"
markers = [
    "smoke: 标记为冒烟测试，验证核心流程是否正常",
]

[tool.basedpyright]
venvPath = "."
venv = ".venv"
pythonVersion = "3.14"
extraPaths = ["apps/web-service", "packages/duyi-utils/src"]

[tool.pylint.messages_control]
disable = ["global-statement"]